# Generated by Django 4.2.30 on 2026-06-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0009_drop_legacy_pending_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_job_hunt',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='JobHuntProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_roles', models.JSONField(default=list, help_text='List of target job roles')),
                ('resume_url', models.URLField(blank=True, max_length=500)),
                ('years_experience', models.CharField(blank=True, max_length=100)),
                ('current_role', models.CharField(blank=True, max_length=300)),
                ('current_company', models.CharField(blank=True, max_length=300)),
                ('skills', models.TextField(blank=True, help_text='Key skills and technologies')),
                ('target_companies', models.JSONField(blank=True, default=list)),
                ('target_locations', models.JSONField(blank=True, default=list)),
                ('standout_points', models.TextField(blank=True)),
                ('message_tone', models.CharField(default='professional', max_length=100)),
                ('education', models.TextField(blank=True)),
                ('experience_details', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('additional_context', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_hunt_profile', to='linkedin.campaign')),
            ],
        ),
    ]
