# Generated by Django 4.2.30 on 2026-06-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0010_campaign_is_job_hunt_jobhuntprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='is_freemium',
        ),
    ]
