# Generated by Django 4.2.30 on 2026-06-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0011_remove_campaign_is_freemium'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhuntprofile',
            name='resume_text',
            field=models.TextField(blank=True, default='', help_text='Raw text extracted from uploaded resume PDF'),
        ),
    ]
